import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle, Sparkles } from "lucide-react";

const faqs = [
  {
    question: "How does SiteForge AI generate websites?",
    answer:
      "SiteForge AI uses advanced large language models trained on millions of high-quality websites. When you describe your website idea, the AI generates clean, semantic HTML, CSS, and JavaScript code that matches your requirements. You can then preview, edit, and export the code.",
  },
  {
    question: "Do I need coding knowledge to use SiteForge?",
    answer:
      "No coding knowledge is required! Simply describe the website you want in natural language, and our AI handles the rest. However, if you are a developer, you can also access and modify the generated code directly.",
  },
  {
    question: "Can I export the code and host it anywhere?",
    answer:
      "Absolutely! The code generated by SiteForge AI is yours to keep. You can download the complete HTML, CSS, and JavaScript files and host them on any platform — Netlify, Vercel, GitHub Pages, or your own server.",
  },
  {
    question: "What types of websites can I build?",
    answer:
      "You can build virtually any type of website: landing pages, portfolios, e-commerce stores, blogs, SaaS websites, agency sites, restaurant pages, and more. The AI adapts to your specific requirements.",
  },
  {
    question: "How long does it take to generate a website?",
    answer:
      "Most websites are generated in 30-60 seconds. Complex multi-page sites with custom functionality may take slightly longer. You can watch the AI build your site in real-time with our live preview panel.",
  },
  {
    question: "Is there a free plan available?",
    answer:
      "Yes! We offer a free tier that lets you generate up to 3 websites per month. For unlimited generations and advanced features like custom domains and priority support, check out our Pro and Enterprise plans.",
  },
  {
    question: "Can I use SiteForge AI for client projects?",
    answer:
      "Yes, absolutely! Many freelance designers and agencies use SiteForge AI to rapidly prototype and build websites for their clients. The exported code is clean and production-ready.",
  },
  {
    question: "What technologies does the generated code use?",
    answer:
      "Generated websites use modern, production-ready technologies including HTML5, CSS3 (with Tailwind CSS), and vanilla JavaScript. React and TypeScript support are available on Pro and Enterprise plans.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="relative py-24 sm:py-32">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-indigo-950/10 to-transparent" />

      <div className="relative mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/20 bg-violet-500/5 px-3 py-1 text-xs text-violet-300 mb-4">
            <Sparkles className="h-3 w-3" />
            FAQ
          </div>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Frequently Asked{" "}
            <span className="bg-gradient-to-r from-violet-400 to-indigo-300 bg-clip-text text-transparent">
              Questions
            </span>
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto text-lg">
            Everything you need to know about building websites with SiteForge AI.
          </p>
        </motion.div>

        {/* FAQ Accordion */}
        <div className="space-y-3">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.05 }}
              className="rounded-xl border border-white/[0.08] bg-white/[0.02] overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full flex items-center justify-between gap-4 px-6 py-4 text-left"
              >
                <div className="flex items-center gap-3">
                  <HelpCircle className="h-5 w-5 text-violet-400 shrink-0" />
                  <span className="text-sm font-medium text-white">{faq.question}</span>
                </div>
                <motion.div
                  animate={{ rotate: openIndex === index ? 180 : 0 }}
                  transition={{ duration: 0.2 }}
                  className="shrink-0"
                >
                  <ChevronDown className="h-5 w-5 text-gray-500" />
                </motion.div>
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-4 pl-14">
                      <p className="text-sm text-gray-400 leading-relaxed">{faq.answer}</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
